# Use the official Python base image 
FROM python:3.9-slim 
# Set the working directory 
WORKDIR /workspace 
# Install Jupyter 
RUN pip install jupyter 
# Install any additional Python packages here 
# COPY requirements.txt ./ # RUN pip install -r requirements.txt 
# Expose the Jupyter port 
EXPOSE 8888 
# Set the default command to start Jupyter Notebook 
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]